In [44]:
import pandas as pd
import json
import requests

In [45]:
data = pd.read_csv("prueba.csv")
data = data.drop(columns=['Unnamed: 0'])  # Elimina columna innecesaria
data.columns = data.columns.str.strip()

In [46]:
print(data.columns.tolist())

['Bankrupt?', 'ROA(C) before interest and depreciation before interest', 'ROA(A) before interest and % after tax', 'ROA(B) before interest and depreciation after tax', 'Operating Gross Margin', 'Realized Sales Gross Margin', 'Operating Profit Rate', 'Pre-tax net Interest Rate', 'After-tax net Interest Rate', 'Non-industry income and expenditure/revenue', 'Continuous interest rate (after tax)', 'Operating Expense Rate', 'Research and development expense rate', 'Cash flow rate', 'Interest-bearing debt interest rate', 'Tax rate (A)', 'Net Value Per Share (B)', 'Net Value Per Share (A)', 'Net Value Per Share (C)', 'Persistent EPS in the Last Four Seasons', 'Cash Flow Per Share', 'Revenue Per Share (Yuan ¥)', 'Operating Profit Per Share (Yuan ¥)', 'Per Share Net profit before tax (Yuan ¥)', 'Realized Sales Gross Profit Growth Rate', 'Operating Profit Growth Rate', 'After-tax Net Profit Growth Rate', 'Regular Net Profit Growth Rate', 'Continuous Net Profit Growth Rate', 'Total Asset Growth Rate', 'Net Value Growth Rate', 'Total Asset Return Growth Rate Ratio', 'Cash Reinvestment %', 'Current Ratio', 'Quick Ratio', 'Interest Expense Ratio', 'Total debt/Total net worth', 'Debt ratio %', 'Net worth/Assets', 'Long-term fund suitability ratio (A)', 'Borrowing dependency', 'Contingent liabilities/Net worth', 'Operating profit/Paid-in capital', 'Net profit before tax/Paid-in capital', 'Inventory and accounts receivable/Net value', 'Total Asset Turnover', 'Accounts Receivable Turnover', 'Average Collection Days', 'Inventory Turnover Rate (times)', 'Fixed Assets Turnover Frequency', 'Net Worth Turnover Rate (times)', 'Revenue per person', 'Operating profit per person', 'Allocation rate per person', 'Working Capital to Total Assets', 'Quick Assets/Total Assets', 'Current Assets/Total Assets', 'Cash/Total Assets', 'Quick Assets/Current Liability', 'Cash/Current Liability', 'Current Liability to Assets', 'Operating Funds to Liability', 'Inventory/Working Capital', 'Inventory/Current Liability', 'Current Liabilities/Liability', 'Working Capital/Equity', 'Current Liabilities/Equity', 'Long-term Liability to Current Assets', 'Retained Earnings to Total Assets', 'Total income/Total expense', 'Total expense/Assets', 'Current Asset Turnover Rate', 'Quick Asset Turnover Rate', 'Working capitcal Turnover Rate', 'Cash Turnover Rate', 'Cash Flow to Sales', 'Fixed Assets to Assets', 'Current Liability to Liability', 'Current Liability to Equity', 'Equity to Long-term Liability', 'Cash Flow to Total Assets', 'Cash Flow to Liability', 'CFO to Assets', 'Cash Flow to Equity', 'Current Liability to Current Assets', 'Liability-Assets Flag', 'Net Income to Total Assets', 'Total assets to GNP price', 'No-credit Interval', 'Gross Profit to Sales', "Net Income to Stockholder's Equity", 'Liability to Equity', 'Degree of Financial Leverage (DFL)', 'Interest Coverage Ratio (Interest expense to EBIT)', 'Net Income Flag', 'Equity to Liability']

In [47]:
# Lista de columnas que el modelo espera (ajustada a los nombres reales del CSV después de .str.strip())
features = [
    'ROA(C) before interest and depreciation before interest',
    'ROA(A) before interest and % after tax',
    'ROA(B) before interest and depreciation after tax',
    'Net Value Per Share (B)',
    'Net Value Per Share (A)',
    'Net Value Per Share (C)',
    'Persistent EPS in the Last Four Seasons',
    'Operating Profit Per Share (Yuan ¥)',
    'Per Share Net profit before tax (Yuan ¥)',
    'Debt ratio %',
    'Net worth/Assets',
    'Borrowing dependency',
    'Operating profit/Paid-in capital',
    'Net profit before tax/Paid-in capital',
    'Inventory and accounts receivable/Net value',
    'Working Capital to Total Assets',
    'Current Liability to Assets',
    'Working Capital/Equity',
    'Current Liabilities/Equity',
    'Retained Earnings to Total Assets',
    'Total expense/Assets',
    'Current Liability to Equity',
    'Equity to Long-term Liability',
    'Current Liability to Current Assets',
    'Liability-Assets Flag',
    'Net Income to Total Assets',
    "Net Income to Stockholder's Equity",
    'Liability to Equity'
]

In [49]:
# -------------------------------
# 3. Validar columnas existentes
# -------------------------------
missing = [f for f in features if f not in data.columns]
if missing:
    print("Las siguientes columnas faltan en tu archivo CSV:")
    print(missing)
else:
    # -------------------------------
    # 4. Filtrar y convertir a JSON
    # -------------------------------
    data_filtered = data[features]
    data_dict = data_filtered.to_dict(orient='list')
    data_json = json.dumps({"data": [data_dict]})

    # -------------------------------
    # 5. Leer URI del endpoint
    # -------------------------------
    with open("uri.json", "r") as suri:
        scoring_uri = json.load(suri)["URI"][0]

    # -------------------------------
    # 6. Enviar petición al endpoint
    # -------------------------------
    headers = {"Content-Type": "application/json"}
    response = requests.post(scoring_uri, data=data_json, headers=headers)

    # -------------------------------
    # 7. Mostrar resultados
    # -------------------------------
    if response.status_code == 200:
        result = json.loads(response.json())
        data["Bankcrupt"] = result
        display(data)
    else:
        print(f"Error en la predicción: {response.text}")

,Bankrupt?,ROA(C) before interest and depreciation before interest,ROA(A) before interest and % after tax,ROA(B) before interest and depreciation after tax,Operating Gross Margin,Realized Sales Gross Margin,Operating Profit Rate,Pre-tax net Interest Rate,After-tax net Interest Rate,Non-industry income and expenditure/revenue,...,Total assets to GNP price,No-credit Interval,Gross Profit to Sales,Net Income to Stockholder's Equity,Liability to Equity,Degree of Financial Leverage (DFL),Interest Coverage Ratio (Interest expense to EBIT),Net Income Flag,Equity to Liability,Bankcrupt
0,0,302583.846829,215926.668338,160681.375234,113789.973083,363023.506580,21337.201274,391837.887305,401233.992710,-3081.409915,...,-31727.661064,254483.525085,91398.771828,185869.684595,56136.475541,6439.213877,194339.999725,218748,-21751.619260,NaN
1,0,296828.273778,213045.320105,155028.177793,111604.727814,357377.710979,21333.981513,391764.751701,401162.054605,-3081.382844,...,-32506.279096,251459.324081,89736.384811,186528.801063,63877.101621,6446.586494,194383.053127,218748,-30299.884588,NaN
2,0,327271.457125,234716.999128,172092.136838,114193.628800,364066.390738,21337.086282,392031.534720,401360.048787,-3074.991683,...,-30668.672365,251464.519612,91705.142213,186246.487611,55978.622787,6426.802673,194262.498897,218748,-18209.737872,NaN
3,1,269715.726612,192432.598125,142886.849135,109683.693560,352414.530463,21329.381856,391660.207706,401078.740547,-3081.355773,...,-27070.202705,251224.732013,88276.137513,185237.572268,58382.352910,6204.241904,187676.849320,218748,-29077.210429,NaN
4,0,322100.206211,225137.131923,173448.904224,113136.784740,361335.930397,21336.807017,391821.994810,401217.421958,-3081.631403,...,-32166.781557,250142.316882,90901.039680,186230.436500,56715.036089,6434.530874,194311.528008,218748,-26386.100504,NaN
5,0,287800.496758,205263.217183,150540.408748,111140.523739,356173.653815,21333.114149,391748.557926,401150.086840,-3081.267178,...,-28434.561754,251408.065819,89383.825463,185875.550424,57709.995625,6441.210105,194351.866011,218748,-28496.495732,NaN
6,0,289348.950422,207184.116005,153619.227046,112415.708846,359472.960060,21334.106361,391770.174732,401170.076953,-3081.301632,...,-22364.276630,251398.005486,90352.769763,185871.470625,56714.641320,6442.092860,194357.063173,218748,-26384.535195,NaN
7,1,252361.359138,181128.847362,133615.605332,111678.119762,357567.326280,21332.325637,391628.949955,401066.707025,-3084.582116,...,-32513.768574,251241.135760,89792.593103,185154.893963,57580.732969,6396.280314,194039.800334,218748,-28340.347833,NaN
8,0,344070.718569,233264.011557,181311.197280,116030.262313,368124.158189,21339.918357,391902.963683,401261.742144,-3081.318859,...,-26092.502522,238024.075425,93102.294268,186386.240393,56728.261505,6427.416966,194266.493014,218748,-26437.924626,NaN
9,0,282191.004241,203982.617968,150679.564377,114184.454806,364042.688825,21331.116584,391896.109574,401297.711196,-3074.944925,...,-29021.142846,251018.642896,91698.156767,185792.157626,56500.961406,6460.832308,194460.613492,218748,-25342.485140,NaN